# Generated by Django 4.0.1 on 2022-02-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='codigo',
        ),
    ]
