# Generated by Django 4.0.1 on 2022-02-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0004_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
