# Generated by Django 4.0.1 on 2022-02-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0005_report_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='static/', verbose_name='Imagen'),
        ),
    ]
