# Generated by Django 4.0.1 on 2022-02-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0007_alter_report_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
