# Generated by Django 4.0.1 on 2022-02-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('text', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='media/', verbose_name='Imagen')),
            ],
        ),
    ]
